tls-listening-port=5349

external-ip=111.111.111.111
relay-ip=111.111.111.111

min-port=49152
max-port=65535
use-auth-secret
static-auth-secret=2Uc8N2Xb1eBKR4DL6xnCrxVXXoxKZzqBJNVedBDq9GV1v5ukWJoIkTjmqSIbeaZH

userdb=/var/lib/coturn/turndb
user=element-livekit-call-user:element-livekit-call-user-pass

realm=turn.example.com

user-quota=12
total-quota=1200

no-tcp-relay
cert=/certs/fullchain.crt
pkey=/certs/privkey.key
log-file=/var/tmp/turn.log

pidfile="/var/run/turnserver.pid"

no-cli
mobility
no-tlsv1
no-tlsv1_1
no-multicast-peers
fingerprint