tls-listening-port={{TURN_TLS_PORT}}
external-ip={{TURN_EXTERNAL_IP}}
relay-ip={{TURN_RELAY_IP}}
min-port={{TURN_MIN_PORT}}
max-port={{TURN_MAX_PORT}}
use-auth-secret
static-auth-secret={{TURN_SHARED_SECRET}}
userdb=/var/lib/coturn/turndb
user={{TURN_USER}}:{{TURN_PASSWORD}}
realm={{TURN_REALM}}
user-quota={{TURN_USER_QUOTA}}
total-quota={{TURN_TOTAL_QUOTA}}
no-tcp-relay
cert=/certs/fullchain.crt
pkey=/certs/privkey.key
log-file=/var/tmp/turn.log
pidfile="/var/run/turnserver.pid"
no-cli
mobility
no-tlsv1
no-tlsv1_1
no-multicast-peers
fingerprint
